# Sample .travis.yml for R projects

language: r
cache: apt
warnings_are_errors: false
sudo: required
before_install:
  - Rscript -e 'install.packages(c("stringi","magrittr"), repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages(c("stringr",  "colorspace"), repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("reshape2", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("munsell", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("scales", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("ggplot2", repos = "http://cran.rstudio.com")'
env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
